### ISSUE TITLE
windows compatibility

### ISSUE THREAD

**Issue by niccord** [KieferSivitz/vue-gh-pages#6]
I had some troubles using this package on windows:
`Creating production build
Build Complete.
{ Error: Command failed: rm -r dist
"rm" not recognized
    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) killed: false, code: 1, signal: null, cmd: 'rm -r dist' }`

I modified index.js skipping that command and I got 
`if (err) throw err;
Error: ENOENT: no such file or directory, open 'C:\<path>\docs\index.html'
    at Error (native)`

**Comment by KieferSivitz** [comment]
Looks like I forgot about cmd prompt. The problem was the 'rm' command not being present on windows command prompt. Workaround on 1.7.3 is git bash I guess. Anyway, I just updated it and 1.7.4 should have this resolved.

**Comment by niccord** [comment]
Awesome! Nice job
